all:
	@echo "make [task1 | task2 ...]"

task1:
	g++ -Wall  -fsanitize=address tree1.cpp -std=c++17 -o task1 && ./task1 && rm task1

task2:
	g++ -Wall  -fsanitize=address task2.cpp -std=c++17 -o task1 && ./task1 && rm task1

task3:
	g++ -Wall  -fsanitize=address task3.cpp -std=c++17 -o task1 && ./task1 && rm task1

task4:
	g++ -Wall  -fsanitize=address task4.cpp -std=c++17 -o task1 && ./task1 && rm task1

task5:
	g++ -Wall  -fsanitize=address task5.cpp -std=c++17 -o task1 && ./task1 && rm task1

task6:
	g++ -Wall  -fsanitize=address task6.cpp -std=c++17 -o task1 && ./task1 && rm task1